//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Katonk.RealEstate.Zillow
{
    using System.Xml.Serialization;

    public partial class Results
    {
        private Message _messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "message", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Message Message
        {
            get
            {
                return this._messageField;
            }
            set
            {
                this._messageField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/SearchResults.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "searchresults", Namespace = "http://www.zillow.com/static/xsd/SearchResults.xsd", IsNullable = false)]
    public partial class SearchResults : Results
    {
        private SearchResultsRequest _requestField;

        private SearchResultsResponse _responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "request", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SearchResultsRequest Request
        {
            get
            {
                return this._requestField;
            }
            set
            {
                this._requestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "response", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SearchResultsResponse Response
        {
            get
            {
                return this._responseField;
            }
            set
            {
                this._responseField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/Zestimate.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "zestimate", Namespace = "http://www.zillow.com/static/xsd/Zestimate.xsd", IsNullable = false)]
    public partial class ZestimateResults : Results
    {
        private ZestimateRequest _requestField;

        private DetailedProperty _responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "request", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZestimateRequest Request
        {
            get
            {
                return this._requestField;
            }
            set
            {
                this._requestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "response", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DetailedProperty DetailedProperty
        {
            get
            {
                return this._responseField;
            }
            set
            {
                this._responseField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "updatedPropertyDetails", Namespace = "http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd", IsNullable = false)]
    public partial class UpdatedPropertyDetailsResults : Results
    {
        private UpdatedPropertyDetailsRequest _requestField;

        private UpdatedPropertyDetailsResponse _responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "request", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UpdatedPropertyDetailsRequest Request
        {
            get
            {
                return this._requestField;
            }
            set
            {
                this._requestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "response", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UpdatedPropertyDetailsResponse Response
        {
            get
            {
                return this._responseField;
            }
            set
            {
                this._responseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("searchresultsRequest", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class SearchResultsRequest
    {

        private string _addressField;

        private string _cityStateZipField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "address", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address
        {
            get
            {
                return this._addressField;
            }
            set
            {
                this._addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "citystatezip", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CityStateZip
        {
            get
            {
                return this._cityStateZipField;
            }
            set
            {
                this._cityStateZipField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("request", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/Zestimate.xsd")]
    public partial class ZestimateRequest
    {

        private string _zpIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "zpid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZpId
        {
            get
            {
                return this._zpIdField;
            }
            set
            {
                this._zpIdField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("request", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd")]
    public partial class UpdatedPropertyDetailsRequest
    {

        private string _zpIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "zpid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZpId
        {
            get
            {
                return this._zpIdField;
            }
            set
            {
                this._zpIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Regions", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class Regions
    {

        private string _zipCodeIdField;

        private string _cityIdField;

        private string _countyIdField;

        private string _stateIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zipcode-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string ZipCodeId
        {
            get
            {
                return this._zipCodeIdField;
            }
            set
            {
                this._zipCodeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("city-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string CityId
        {
            get
            {
                return this._cityIdField;
            }
            set
            {
                this._cityIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("county-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string CountyId
        {
            get
            {
                return this._countyIdField;
            }
            set
            {
                this._countyIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("state-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string StateId
        {
            get
            {
                return this._stateIdField;
            }
            set
            {
                this._stateIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("AmountOptional", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class AmountOptional
    {

        private Currency _currencyField;

        private bool _currencyFieldSpecified;

        private string _durationField;

        private bool _deprecatedField;

        private bool _deprecatedFieldSpecified;

        private string _valueField;

        public AmountOptional()
        {
            this._deprecatedField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("currency")]
        public Currency Currency
        {
            get
            {
                return this._currencyField;
            }
            set
            {
                this._currencyField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool currencySpecified {
        //    get {
        //        return this._currencyFieldSpecified;
        //    }
        //    set {
        //        this._currencyFieldSpecified = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("duration", DataType = "integer")]
        public string Duration
        {
            get
            {
                return this._durationField;
            }
            set
            {
                this._durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("deprecated")]
        public bool Deprecated
        {
            get
            {
                return this._deprecatedField;
            }
            set
            {
                this._deprecatedField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool deprecatedSpecified {
        //    get {
        //        return this._deprecatedFieldSpecified;
        //    }
        //    set {
        //        this._deprecatedFieldSpecified = value;
        //    }
        //}

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this._valueField;
            }
            set
            {
                this._valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Currency", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public enum Currency
    {

        /// <remarks/>
        USD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Zestimate", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class Zestimate
    {

        private Amount _amountField;

        private string _lastUpdatedField;

        private AmountOptional _oneWeekChangeField;

        private AmountOptional _valueChangeField;

        private ZestimateValuationRange _valuationRangeField;

        private string _percentileField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("amount", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Amount Amount
        {
            get
            {
                return this._amountField;
            }
            set
            {
                this._amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-updated", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastUpdated
        {
            get
            {
                return this._lastUpdatedField;
            }
            set
            {
                this._lastUpdatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("oneWeekChange", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmountOptional OneWeekChange
        {
            get
            {
                return this._oneWeekChangeField;
            }
            set
            {
                this._oneWeekChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueChange", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmountOptional ValueChange
        {
            get
            {
                return this._valueChangeField;
            }
            set
            {
                this._valueChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valuationRange", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZestimateValuationRange ValuationRange
        {
            get
            {
                return this._valuationRangeField;
            }
            set
            {
                this._valuationRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("percentile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Percentile
        {
            get
            {
                return this._percentileField;
            }
            set
            {
                this._percentileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Amount", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class Amount
    {

        private Currency _currencyField;

        private string _valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("currency")]
        public Currency Currency
        {
            get
            {
                return this._currencyField;
            }
            set
            {
                this._currencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
        public string Value
        {
            get
            {
                return this._valueField;
            }
            set
            {
                this._valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("ZestimateValuationRange", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class ZestimateValuationRange
    {

        private Amount _lowField;

        private Amount _highField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("low", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Amount Low
        {
            get
            {
                return this._lowField;
            }
            set
            {
                this._lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("high", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Amount High
        {
            get
            {
                return this._highField;
            }
            set
            {
                this._highField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Address", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class Address
    {

        private string _streetField;

        private string _zipCodeField;

        private string _cityField;

        private string _stateField;

        private decimal _latitudeField;

        private decimal _longitudeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("street", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Street
        {
            get
            {
                return this._streetField;
            }
            set
            {
                this._streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zipcode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZipCode
        {
            get
            {
                return this._zipCodeField;
            }
            set
            {
                this._zipCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("city", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City
        {
            get
            {
                return this._cityField;
            }
            set
            {
                this._cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("state", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State
        {
            get
            {
                return this._stateField;
            }
            set
            {
                this._stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("latitude", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Latitude
        {
            get
            {
                return this._latitudeField;
            }
            set
            {
                this._latitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("longitude", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Longitude
        {
            get
            {
                return this._longitudeField;
            }
            set
            {
                this._longitudeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("DeprecatedType", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class DeprecatedType
    {

        private bool _deprecatedField;

        private string _valueField;

        public DeprecatedType()
        {
            this._deprecatedField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("deprecated")]
        public bool Deprecated
        {
            get
            {
                return this._deprecatedField;
            }
            set
            {
                this._deprecatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this._valueField;
            }
            set
            {
                this._valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Links", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class Links
    {

        private string _homeDetailsField;

        private string _graphsAndDataField;

        private string _mapThisHomeField;

        private string _myEstimatorField;

        private DeprecatedType _myZestimatorField;

        private string _comparablesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("homedetails", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HomeDetails
        {
            get
            {
                return this._homeDetailsField;
            }
            set
            {
                this._homeDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("graphsanddata", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GraphsAndData
        {
            get
            {
                return this._graphsAndDataField;
            }
            set
            {
                this._graphsAndDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mapthishome", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MapThisHome
        {
            get
            {
                return this._mapThisHomeField;
            }
            set
            {
                this._mapThisHomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("myestimator", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MyEstimator
        {
            get
            {
                return this._myEstimatorField;
            }
            set
            {
                this._myEstimatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("myzestimator", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DeprecatedType MyZestimator
        {
            get
            {
                return this._myZestimatorField;
            }
            set
            {
                this._myZestimatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comparables", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comparables
        {
            get
            {
                return this._comparablesField;
            }
            set
            {
                this._comparablesField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimpleProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetailedProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparableProperty))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Property", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class Property
    {

        private uint _zpidField;

        private Links _linksField;

        private Address _addressField;

        private string _fipsCountyField;

        private string _useCodeField;

        private string _taxAssessmentYearField;

        private string _taxAssessmentField;

        private string _yearBuiltField;

        private string _lotSizeSqFtField;

        private string _finishedSqFtField;

        private string _bathroomsField;

        private string _bedroomsField;

        private string _totalRoomsField;

        private string _lastSoldDateField;

        private Amount _lastSoldPriceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zpid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint ZpId
        {
            get
            {
                return this._zpidField;
            }
            set
            {
                this._zpidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("links", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Links Links
        {
            get
            {
                return this._linksField;
            }
            set
            {
                this._linksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Address Address
        {
            get
            {
                return this._addressField;
            }
            set
            {
                this._addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FIPScounty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fipscounty
        {
            get
            {
                return this._fipsCountyField;
            }
            set
            {
                this._fipsCountyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("useCode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UseCode
        {
            get
            {
                return this._useCodeField;
            }
            set
            {
                this._useCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taxAssessmentYear", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaxAssessmentYear
        {
            get
            {
                return this._taxAssessmentYearField;
            }
            set
            {
                this._taxAssessmentYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taxAssessment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaxAssessment
        {
            get
            {
                return this._taxAssessmentField;
            }
            set
            {
                this._taxAssessmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("yearBuilt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YearBuilt
        {
            get
            {
                return this._yearBuiltField;
            }
            set
            {
                this._yearBuiltField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lotSizeSqFt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LotSizeSqFt
        {
            get
            {
                return this._lotSizeSqFtField;
            }
            set
            {
                this._lotSizeSqFtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("finishedSqFt", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FinishedSqFt
        {
            get
            {
                return this._finishedSqFtField;
            }
            set
            {
                this._finishedSqFtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bathrooms", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bathrooms
        {
            get
            {
                return this._bathroomsField;
            }
            set
            {
                this._bathroomsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bedrooms", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bedrooms
        {
            get
            {
                return this._bedroomsField;
            }
            set
            {
                this._bedroomsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totalRooms", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotalRooms
        {
            get
            {
                return this._totalRoomsField;
            }
            set
            {
                this._totalRoomsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lastSoldDate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastSoldDate
        {
            get
            {
                return this._lastSoldDateField;
            }
            set
            {
                this._lastSoldDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lastSoldPrice", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Amount LastSoldPrice
        {
            get
            {
                return this._lastSoldPriceField;
            }
            set
            {
                this._lastSoldPriceField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetailedProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparableProperty))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("SimpleProperty", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class SimpleProperty : Property
    {

        private Zestimate _zestimateField;

        private Zestimate _rentzestimateField;

        private LocalRealEstateRegion[] _localRealEstateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zestimate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zestimate Zestimate
        {
            get
            {
                return this._zestimateField;
            }
            set
            {
                this._zestimateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rentzestimate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Zestimate Rentzestimate
        {
            get
            {
                return this._rentzestimateField;
            }
            set
            {
                this._rentzestimateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("region", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LocalRealEstateRegion[] LocalRealEstate
        {
            get
            {
                return this._localRealEstateField;
            }
            set
            {
                this._localRealEstateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRealEstateRegion", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class LocalRealEstateRegion
    {

        private string _zindexValueField;

        private string _zindexOneYearChangeField;

        private LocalRealEstateRegionLinks _linksField;

        private string _nameField;

        private string _typeField;

        private uint _idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zindexValue", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZindexValue
        {
            get
            {
                return this._zindexValueField;
            }
            set
            {
                this._zindexValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zindexOneYearChange", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZindexOneYearChange
        {
            get
            {
                return this._zindexOneYearChangeField;
            }
            set
            {
                this._zindexOneYearChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("links", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LocalRealEstateRegionLinks Links
        {
            get
            {
                return this._linksField;
            }
            set
            {
                this._linksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name
        {
            get
            {
                return this._nameField;
            }
            set
            {
                this._nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type
        {
            get
            {
                return this._typeField;
            }
            set
            {
                this._typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public uint Id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRealEstateRegionLinks", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class LocalRealEstateRegionLinks
    {

        private string _overviewField;

        private string _forSaleByOwnerField;

        private string _forSaleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("overview", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Overview
        {
            get
            {
                return this._overviewField;
            }
            set
            {
                this._overviewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forSaleByOwner", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ForSaleByOwner
        {
            get
            {
                return this._forSaleByOwnerField;
            }
            set
            {
                this._forSaleByOwnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forSale", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ForSale
        {
            get
            {
                return this._forSaleField;
            }
            set
            {
                this._forSaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("DetailedProperty", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class DetailedProperty : SimpleProperty
    {

        private Regions _regionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Regions Regions
        {
            get
            {
                return this._regionsField;
            }
            set
            {
                this._regionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("ComparableProperty", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class ComparableProperty : SimpleProperty
    {

        private decimal _scoreField;

        private bool _scoreFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("score")]
        public decimal Score
        {
            get
            {
                return this._scoreField;
            }
            set
            {
                this._scoreField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool ScoreSpecified {
        //    get {
        //        return this._scoreFieldSpecified;
        //    }
        //    set {
        //        this._scoreFieldSpecified = value;
        //    }
        //}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("Message", Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class Message
    {

        private string _textField;

        private string _codeField;

        private bool _limitWarningField;

        private bool _limitWarningFieldSpecified;

        public Message()
        {
            this._limitWarningField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("text", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text
        {
            get
            {
                return this._textField;
            }
            set
            {
                this._textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("code", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string Code
        {
            get
            {
                return this._codeField;
            }
            set
            {
                this._codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("limit-warning", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool LimitWarning
        {
            get
            {
                return this._limitWarningField;
            }
            set
            {
                this._limitWarningField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool limitwarningSpecified {
        //    get {
        //        return this._limitWarningFieldSpecified;
        //    }
        //    set {
        //        this._limitWarningFieldSpecified = value;
        //    }
        //}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("searchresultsResponse", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")]
    public partial class SearchResultsResponse
    {

        private SimpleProperty[] _resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("results", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public SimpleProperty[] Results
        {
            get
            {
                return this._resultsField;
            }
            set
            {
                this._resultsField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("updatedPropertyDetailsResponse", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd")]
    public partial class UpdatedPropertyDetailsResponse
    {
        private SimpleProperty[] _resultsField;

        [System.Xml.Serialization.XmlElementAttribute("zpid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint ZpId
        {
            get;
            set;
        }

        [System.Xml.Serialization.XmlElementAttribute("pageViewCount", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PageViewCount PageViewCount
        {
            get;
            set;
        }

        [System.Xml.Serialization.XmlElementAttribute("address", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Address Address
        {
            get;
            set;
        }
    }

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("pageViewCount", AnonymousType = true, Namespace = "http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd")]
    public partial class PageViewCount
    {
        [System.Xml.Serialization.XmlElementAttribute("currentMonth", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint CurrentMonth
        {
            get;
            set;
        }

        [System.Xml.Serialization.XmlElementAttribute("total", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public uint Total
        {
            get;
            set;
        }
    }
}
